### PR TITLE
fix(cni-server): use container id to name veth pair

### PR DESCRIPTION
**Pull request by wu-cl**
Before, veth pair was named veth-"ns". 
But in some cases, kubelet will not pass interface info to cni DELETE op. 
So that, DELETE process will be failed and ip will not be released.

#176

### CODE REVIEW

**Review by KeyongSun — APPROVED** [review]
The add port error information seem not  accurate: 
L171: "return s.RetError(cnipb.ErrorCode_IO_FAILURE, "exec error in namespace", err)"

**Comment by wu-cl** [comment]
@KeyongSun  L171: "return s.RetError(cnipb.ErrorCode_IO_FAILURE, "exec error in namespace", err)"

**Comment by KeyongSun** [comment]
> @KeyongSun L171: "return s.RetError(cnipb.ErrorCode_IO_FAILURE, "exec error in namespace", err)" The last parameter err will be the detail error
> 
> ```
> if err != nil {
>     klog.Errorf("create veth device error, err: %s", err)
>     return err
> }
> ```
Previous the interface id generated with veth+NS, but now changed to containerID, add the ovsdbPort error not related to namespace now, I mean the  "exec error in namespace"

**Comment by wu-cl** [comment]
> > @KeyongSun L171: "return s.RetError(cnipb.ErrorCode_IO_FAILURE, "exec error in namespace", err)" The last parameter err will be the detail error
> > ```
> > if err != nil {
> >     klog.Errorf("create veth device error, err: %s", err)
> >     return err
> > }
> > ```
> 
> Previous the interface id generated with veth+NS, but now changed to containerID, add the ovsdbPort error not related to namespace now, I mean the "exec error in namespace"

Sry, I confuse L164 and L171, error info has been changed to "add port to ovs bridge error".
CreatePort func actually just add an existed port to bridge, creation of veth pair occurs at L152.

**Pull request merged**
